name: Build Project

# Esse fluxo vai rodar toda vez que alguém fizer push para a branch 'main' ou criar um pull request
on:
  push:
    branches:
      - main  # Você pode adicionar outras branches que quiser monitorar, como 'develop'
  pull_request:
    branches:
      - main

# Job que será executado
jobs:
  build:
    runs-on: ubuntu-latest  # Usa a última versão do Ubuntu no ambiente do GitHub Actions

    steps:
      # Baixa o código do repositório
      - name: Checkout repository
        uses: actions/checkout@v2

      # Configura o JDK (Spring e Java requerem o Java instalado)
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'  # Você pode ajustar a versão conforme necessário

      # Rodar o Maven build (ou Gradle, se for o caso)
      - name: Build with Maven
        run: mvn clean install --no-transfer-progress

      # (Opcional) Se você quiser rodar testes depois do build:
      - name: Run tests
        run: mvn test
