name: Build & Auto PRs

on:
  push:
    branches:
      - '**'  # Roda em qualquer branch
  pull_request:
    branches:
      - develop
      - main

jobs:
  build-and-promote:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'

      - name: Build with Maven
        run: mvn clean install --no-transfer-progress

      - name: Run tests
        run: mvn test

      # Cria PR automático da feature/branch atual para develop
      - name: Create PR to develop
        if: ${{ github.ref != 'refs/heads/develop' && github.ref != 'refs/heads/main' }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          BRANCH_NAME=$(echo "${GITHUB_REF#refs/heads/}")
          echo "Verificando se já existe PR de $BRANCH_NAME para develop..."
          EXISTING_PR=$(gh pr list --head "$BRANCH_NAME" --base develop --json number -q '.[0].number')
          if [ -z "$EXISTING_PR" ]; then
            gh pr create \
              --base develop \
              --head $BRANCH_NAME \
              --title "Auto PR: $BRANCH_NAME → develop"_
